### ISSUE TITLE
If quote marks or \ is entered into a subscription field, another \ will added to user's entry at Benchmark Email

### ISSUE THREAD

**Issue by randywsandberg** [beAutomated/benchmark-email-lite#11]
Steps to reproduce:
1. Go to http://dev-benchmark-email-lite.pantheonsite.io/
2. For First Name, enter You’re
3. For Last Name, enter Welcome \ not
4. For Email, enter an address you have access and that hasn’t yet been added to the contact
—> see Screenshot 1 for an example
5. Click Subscribe
6. Retrieve the “Please confirm your subscription to our mailing list” email and click the “Click here to confirm your subscription.” link

Result:
At benchmarkemail.com, newly subscribed user’s First Name You’re became You\’re and Last Name Welcome \ not became Welcome \\ not. See Screenshot 2.

Expected result:
Expected First and Last names entered in WordPress to be the same at benchmarkemail.com.

Workaround:
No

Reproducible?
Always

Occurs:
- Mac Safari 9.1.1 + BMEL 2.6 [536c3f2]
- Mac Chrome 51.0.2704.84 (64-bit) + BMEL 2.6 [536c3f2]

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/15979809/2e137058-2f1b-11e6-9732-7c5440e4ddb1.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/15979810/2e153abe-2f1b-11e6-8463-41e60e5164b1.png)

**Comment by seanconklin** [comment]
The backslash (\) is the escape character used in PHP and MySQL and most databases. The backslash itself must be escaped for storage, but single quotes or apostrophes also need to be escaped since those are usually encapsulated in a DB request from PHP. Double quotes are also commonly escaped when the data is placed into a form field, since double quotes contain the values being presented.

The question that comes to mind here is whether PHP is transmitting the escapes over the Benchmark Email API. If so, it could be something can address. If not, that would need to be a topic for Benchmark Email. I'll run some tests and add a comment soon.

**Comment by randywsandberg** [comment]
Also reproducible if one enters double quotes. See screenshots.

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/16024372/5a476a1e-3176-11e6-8e1b-4a4383800382.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/16024373/5a6541ec-3176-11e6-80fa-0ee9213b1ff6.png)

**Comment by seanconklin** [comment]
I added a fix to prevent this in our transmission (see Comm Logs). However, any behaviors within the BME UI are internal to them and may still need to be reported, depending on your findings.

**Comment by randywsandberg** [comment]
Using Win Chrome 51.0.2704.84 m (64-bit) + BMEL 2.6 [e8ac55a] I was not able to reproduce the issue using single nor double quotes (see screenshots 1 - 4). But, I was able to reproduce the issue using a backslash (see screenshots 1 and 2). I'll update the title now.

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/16095211/80831b3c-32f8-11e6-8c06-727414900607.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/16095210/8082ca10-32f8-11e6-892e-e3dcce7d4b44.PNG)
![screenshot 3](https://cloud.githubusercontent.com/assets/19829655/16095212/8085b392-32f8-11e6-8b4c-2b57aecef29a.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/19829655/16095209/8081aca2-32f8-11e6-872c-a1fb11b99740.PNG)
