### ISSUE TITLE
Queue schedule in cron date/time different than Communication Log's date/time format

### ISSUE THREAD

**Issue by randywsandberg** [beAutomated/benchmark-email-lite#15]
The Queue schedule in cron date/time format looks like the old way we used to present the Communication Log date/time format. See Screenshot 1. Just checking to see if this is intentional or not. Plus, it appears to be hard set to GMT time.

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/16064437/154171b8-3256-11e6-98c4-a83a975e2695.png)

**Comment by randywsandberg** [comment]
Changing this from question to bug being that I am pretty sure, beyond the dat/time format, you didn't mean for it to be set at GMT time. :-D

**Comment by seanconklin** [comment]
I also added the (UTC) designation to the column header. Cron jobs are always represented in GMT/UTC time as they are considered locale agnostic. It may be possible to convert them, but WP treats them in GMT/UTC and does not convert them for us.

**Comment by randywsandberg** [comment]
Given that the Communication Log displays the Timezone set in WordPress > Settings > General, I feel, if possible, it would be more helpful if the Queue schedule in cron log could also use the same Timezone. That is, I am betting folks who look at the Queue schedule in cron log will find it much more helpful if they can see when the next attempt to communicate with Benchmark Email will be if the time is displayed in their time as opposed to UTC.

As for the reported date/time format, that looks AWESOME. See screenshot. Thanks Sean! :-)

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/16091793/0f5e25cc-32ea-11e6-929e-2c7421c4b7e5.png)

**Comment by randywsandberg** [comment]
Could not reproduce the issue where UTC time was being displayed for the Queue schedule in cron log. Now, both logs' time zones appear to be the same. See screenshot. Closing as fixed. Way to Code Sean!

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/16098397/97ea88a0-3307-11e6-8969-5f6cbb0e7c41.PNG)
