### ISSUE TITLE
Redundent "Confirm your subscription" email for first user that causes Connection Timeout

### ISSUE THREAD

**Issue by randywsandberg** [beAutomated/benchmark-email-lite#17]
Here's a puzzler for you. If I set the BenchmarkEmail > Settings > Diagnostics > Connection Timeout to 1, then go to the home page and try to make a new subscription I will, as predicted, receive a message from the system stating, "Successfully queued subscription." (see Screenshot 1). Also, as predicted, a Connection Timeout will occur on the site. See Screenshot 2.

But, even though the system stated, "Successfully queued subscription." and there really was a Connection Timeout, the user still received their "Click here to confirm your subscription." email all the while the Connection Timeout was in place. And, once the Connection Timeout was resolved, the queue (see Screenshot 3) send out another "Click here to confirm your subscription." email to the user.

I say "puzzler" above because I have seen more than one follow up email come to the user who causes the Connection Timeout. But I am not quite sure of the steps to reproduce that test case (yet).

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/16093262/02c2405e-32f0-11e6-94ed-170da6e315e3.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/16093264/02c4cac2-32f0-11e6-8f55-df47f31f37e9.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/19829655/16093263/02c356ce-32f0-11e6-9da7-a86c6bbf4c06.png)

**Comment by randywsandberg** [comment]
Hmm, for now, please disregard the "puzzler" part above. Maybe it was just a fluke that I received **FOUR** "Click here to confirm your subscription." email for the user that caused the Connection Timeout. That is, currently, all I can do is reproduce the originally stated issue of a) Connection Timeout occurs, b) User is told their subscription has been queued, c) User is emailed a "Click here to confirm your subscription." email even though the Connection Timeout is still occurring, and d) After the Connection Timeout has been resolved the user is sent another "Click here to confirm your subscription." email.

**Comment by seanconklin** [comment]
When a request is made and not allowed to complete it may still complete on the destination server. This includes the connection dropped by retarding the timeout setting or hitting the normal timeout. If the server fails completely and returns an error we know what to do. If it times out, we have no idea whether the transaction was successful or not. I think we're handling it the best way possible, assuming it failed and re-attempting to be safe. Hopefully with a 20 second timeout we're pretty safe in general. The 10 seconds was insufficient as I observed a single form subscription taking 15 seconds now that we have logs to see it.

**Comment by randywsandberg** [comment]
Agreed. Just wanted to make you aware of the issue that possibly **more** than just two emails were coming to the same user. I will close this for now but let's both keep an eye out for a situation that makes Benchmark Email send more than two "Click here to confirm your subscription." email to the same user!
