### ISSUE TITLE
Changing BODY_HERE to EXCERPT does not save

### ISSUE THREAD

**Issue by seanconklin** [beAutomated/benchmark-email-lite#21]
In the Email Template setting, if you replace BODY_HERE with EXCERPT it will not save. Make it so that the failsafe protection will only block saves that do not contain either one of these, not requiring the BODY_HERE absolutely.

**Comment by seanconklin** [comment]
I've updated the http://make.beautomated.com site to v2.7 in development (set-up WP Pusher from GIT), so assigning for testing.

**Comment by randywsandberg** [comment]
Could NOT reproduce this issue with the latest development BMEL plugin installed at make.beautomated.com. Closing as fixed.
