### ISSUE TITLE
Broken link and links with "www." in them

### ISSUE THREAD

**Issue by randywsandberg** [beAutomated/benchmark-email-lite#24]
1. Clicking Plugins > Benchmark Email Lite > By beautomated link (https://beautomated.com) fails to take user to https://beautomated.wordpress.com.
2. Clicking Plugins > Benchmark Email Lite > Visit link (http://www.beautomated.com/benchmark-email-lite/ takes user to https://beautomated.wordpress.com/benchmark-email-lite/ but the leading "www." isn't necessary.
3. Same as above, editing benchmark-email-lite/wordpress-plugin.php reveals "Plugin URI: http://www.beautomated.com/benchmark-email-lite/" link where the "www." isn't necessary.

**Comment by randywsandberg** [comment]
By the way, version 2.6 of our plugin used different links:
1. For By beAutomated, it used: http://www.beautomated.com/
2. For View details, it used: http://localhost/wordpress/wp-admin/plugin-install.php?tab=plugin-information&plugin=benchmark-email-lite&TB_iframe=true&width=600&height=550
3. For Plugin URI, the same link was used as above: http://www.beautomated.com/benchmark-email-lite/

Thus, the BIG deal here is number 2! Forget about my "www" concern, it's supposed to open a modal box! See screenshot.

![capture](https://user-images.githubusercontent.com/19829655/34466736-94cb39dc-ee93-11e7-8a30-cb240f8b2754.PNG)

**Comment by seanconklin** [comment]
The highlighted link in the screenshot goes to http://beautomated.com in my browser (Safari). It's possible the browser you are using cached the protocol to be https:// from an earlier visit back when the site did not have the redirect. Please try clearing the cache, using another browser, or copy/pasting the link to see what it's showing. Let me know if you continue to see https:// anywhere specifically.

![screen shot 2018-01-01 at 5 39 29 pm](https://user-images.githubusercontent.com/19829621/34472624-d8fdacc0-ef1a-11e7-9c38-1fd97e8d44bf.png)


Also, I have removed the `www.` from the two links within the plugin both in versions 2.6 (WordPress.org SVN) and 2.7 (GitHub) for your review.

**Comment by randywsandberg** [comment]
Something must have changed. None of my browsers can reproduce this now. Even the one you and I easily reproduced it with. And, I did NOT clear the cache. Oh well, it's a mystery! As for the other two links, they look good too. Well done Mr. Conklin! Closing as fixed!
